version: '3'

services:
  app:
    container_name: openlayers-samples
    build: .
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules: {}
